vich_uploader:
    db_driver: orm

    mappings:
        pan_image:
            uri_prefix: /uploads/pans
            upload_destination: '%kernel.project_dir%/public/uploads/pans'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
